name: my_project
sdkPath: .fvm/flutter_sdk
packages:
  - packages/**

scripts:
  postclean: >
    melos exec --flutter --concurrency=3 -- "flutter clean"

  upgrade:
    run: |
      melos exec -- \
        "flutter pub upgrade --major-versions && flutter pub upgrade"
    description: Upgrade the major version of the pub in all packages
    select-package:
      flutter: true
      dir-exists: lib

  analyze:
    run: |
      melos exec --dir-exists="lib" -- \
        "flutter analyze . --fatal-infos"
    description: Analyze in all packages

  format:
    run: |
      melos exec --dir-exists="lib" -- \
        "flutter format --dry-run --set-exit-if-changed lib/"
    description: Format in all packages

  test:
    run: |
      sh scripts/generate_coverage_helper_test.sh &&
      melos exec --fail-fast -- \
        "flutter test --coverage"
    description: flutter test in all packages
    select-package:
      dir-exists: test

  gen:
    run: |
      melos exec -c 1 -- \
        "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Generate code files
    select-package:
      dir-exists: lib
      depends-on: "build_runner"

  fix:
    run: |
      melos exec -- \
        "dart fix --apply lib"
    description: Dart fix
    select-package:
      dir-exists: lib
